[package]
name = "mango_ir"
description = "The Mango programming IR (UNDER CONSTRUCTION)"
version = "0.0.1"
authors = ["Mark <mverleg.noreply@gmail.com>"]
edition = "2018"
homepage = "https://mangocode.org/"
license = "Apache-2.0"
publish = true

[dependencies]
